export const flipItems = [
  {
    title: 'Owl',
    secondary: 'Hoo are you?',
    text: 'Owel lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure cum, est amet delectus, blanditiis voluptatem laborum pariatur consequatur quae voluptate, nisi. Laborum adipisci iste earum distinctio, fugit, quas ipsa impedit.',
    imageSrc: '/images/img-01.jpg',
  },
  {
    title: 'Create amazing SVG animations',
    secondary: 'Hi deer.',
    text: "DrawSVGPlugin allows you to progressively reveal (or hide) SVG strokes to make them look like they're being drawn. MorphSVGPlugin to Morph any SVG shape into any other shape smoothly regardless of the number of points in each. MotionPathPlugin allows you to easily move any object along a path.",
    imageSrc: '/images/img-02.jpg',
  },
  {
    title: 'Supercharge immersive WebGL experiences',
    secondary: 'good',
    text: 'GreenSock is used in some of the most popular Three.js powered WebGL projects. Animate any object in a scene. PixiPlugin makes animating Pixi.js objects with GSAP a breeze. Animate position, scale, color effects and more with all the power and control of GSAP and the rendering speed of Pixi.js.',
    imageSrc: '/images/img-03.jpg',
  },
  {
    title: 'Control performant Canvas animations',
    secondary: 'yeah',
    text: "GSAP makes animating with Canvas even easier by providing an easier way to look and sequence animations. GSAP works great with Adobe Animate and EaseJS through GSAP's EaselJSPlugin.",
    imageSrc: '/images/img-04.jpg',
  },
  {
    title: 'Award winning websites',
    secondary: "I'm trying to sleep here.",
    text: 'GSAP is used on over 8,500,000 sites and over 1,000 sites featured on Awwwards. For some of our favorites, check out our showcase.',
    imageSrc: '/images/img-05.jpg',
  },
  {
    title: 'Owl',
    secondary: 'Hoo are you?',
    text: 'Owel lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure cum, est amet delectus, blanditiis voluptatem laborum pariatur consequatur quae voluptate, nisi. Laborum adipisci iste earum distinctio, fugit, quas ipsa impedit.',
    imageSrc: '/images/img-06.jpg',
  },
  {
    title: 'Create amazing SVG animations',
    secondary: 'Hi deer.',
    text: "DrawSVGPlugin allows you to progressively reveal (or hide) SVG strokes to make them look like they're being drawn. MorphSVGPlugin to Morph any SVG shape into any other shape smoothly regardless of the number of points in each. MotionPathPlugin allows you to easily move any object along a path.",
    imageSrc: '/images/img-07.jpg',
  },
  {
    title: 'Supercharge immersive WebGL experiences',
    secondary: 'good',
    text: 'GreenSock is used in some of the most popular Three.js powered WebGL projects. Animate any object in a scene. PixiPlugin makes animating Pixi.js objects with GSAP a breeze. Animate position, scale, color effects and more with all the power and control of GSAP and the rendering speed of Pixi.js.',
    imageSrc: '/images/img-08.jpg',
  },
  {
    title: 'Control performant Canvas animations',
    secondary: 'yeah',
    text: "GSAP makes animating with Canvas even easier by providing an easier way to look and sequence animations. GSAP works great with Adobe Animate and EaseJS through GSAP's EaselJSPlugin.",
    imageSrc: '/images/img-09.jpg',
  },
  {
    title: 'Award winning websites',
    secondary: "I'm trying to sleep here.",
    text: 'GSAP is used on over 8,500,000 sites and over 1,000 sites featured on Awwwards. For some of our favorites, check out our showcase.',
    imageSrc: '/images/img-10.gif',
  },
  {
    title: 'Owl',
    secondary: 'Hoo are you?',
    text: 'Owel lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure cum, est amet delectus, blanditiis voluptatem laborum pariatur consequatur quae voluptate, nisi. Laborum adipisci iste earum distinctio, fugit, quas ipsa impedit.',
    imageSrc: '/images/img-01.jpg',
  },
  {
    title: 'Create amazing SVG animations',
    secondary: 'Hi deer.',
    text: "DrawSVGPlugin allows you to progressively reveal (or hide) SVG strokes to make them look like they're being drawn. MorphSVGPlugin to Morph any SVG shape into any other shape smoothly regardless of the number of points in each. MotionPathPlugin allows you to easily move any object along a path.",
    imageSrc: '/images/img-02.jpg',
  },
  {
    title: 'Supercharge immersive WebGL experiences',
    secondary: 'good',
    text: 'GreenSock is used in some of the most popular Three.js powered WebGL projects. Animate any object in a scene. PixiPlugin makes animating Pixi.js objects with GSAP a breeze. Animate position, scale, color effects and more with all the power and control of GSAP and the rendering speed of Pixi.js.',
    imageSrc: '/images/img-03.jpg',
  },
  {
    title: 'Control performant Canvas animations',
    secondary: 'yeah',
    text: "GSAP makes animating with Canvas even easier by providing an easier way to look and sequence animations. GSAP works great with Adobe Animate and EaseJS through GSAP's EaselJSPlugin.",
    imageSrc: '/images/img-04.jpg',
  },
  {
    title: 'Award winning websites',
    secondary: "I'm trying to sleep here.",
    text: 'GSAP is used on over 8,500,000 sites and over 1,000 sites featured on Awwwards. For some of our favorites, check out our showcase.',
    imageSrc: '/images/img-05.jpg',
  },
  {
    title: 'Owl',
    secondary: 'Hoo are you?',
    text: 'Owel lorem ipsum dolor sit amet, consectetur adipisicing elit. Iure cum, est amet delectus, blanditiis voluptatem laborum pariatur consequatur quae voluptate, nisi. Laborum adipisci iste earum distinctio, fugit, quas ipsa impedit.',
    imageSrc: '/images/img-06.jpg',
  },
  {
    title: 'Create amazing SVG animations',
    secondary: 'Hi deer.',
    text: "DrawSVGPlugin allows you to progressively reveal (or hide) SVG strokes to make them look like they're being drawn. MorphSVGPlugin to Morph any SVG shape into any other shape smoothly regardless of the number of points in each. MotionPathPlugin allows you to easily move any object along a path.",
    imageSrc: '/images/img-07.jpg',
  },
  {
    title: 'Supercharge immersive WebGL experiences',
    secondary: 'good',
    text: 'GreenSock is used in some of the most popular Three.js powered WebGL projects. Animate any object in a scene. PixiPlugin makes animating Pixi.js objects with GSAP a breeze. Animate position, scale, color effects and more with all the power and control of GSAP and the rendering speed of Pixi.js.',
    imageSrc: '/images/img-08.jpg',
  },
  {
    title: 'Control performant Canvas animations',
    secondary: 'yeah',
    text: "GSAP makes animating with Canvas even easier by providing an easier way to look and sequence animations. GSAP works great with Adobe Animate and EaseJS through GSAP's EaselJSPlugin.",
    imageSrc: '/images/img-09.jpg',
  },
  {
    title: 'Award winning websites',
    secondary: "I'm trying to sleep here.",
    text: 'GSAP is used on over 8,500,000 sites and over 1,000 sites featured on Awwwards. For some of our favorites, check out our showcase.',
    imageSrc: '/images/img-10.gif',
  },
];
